/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package com;
//
//import static org.junit.Assert.assertNotNull;
//import org.junit.Test;
//import com.eomcs.pms.App;
//
//public class AppTest {
//  @Test public void appHasAGreeting() {
//    App classUnderTest = new App();
//    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//  }
//}
